[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
darkbid = "7YWfupxWKmgekRxzrWUUgoWEGSoGS2kz9nyaEbzKHqFK"

[provider]
cluster = "localnet"
wallet = '~\.config\solana\id.json'

[scripts]
test = "cargo test"

[hooks]
